name: Build
on: push

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Build via cmake and make
        run: |
             mkdir build
             cd build
             cmake ..
             make
